### ISSUE TITLE
Add TypeScript support

### ISSUE THREAD

**Issue by mattnedrich** [wrr/connect-wwwhisper#13]
It would be nice to add TypeScript support to allow this module to automatically be imported with type information.

**Comment by wrr** [comment]
@mattnedrich as a no TypeScript user do I understand correctly that this can be done without switching the implementation to use TypeScript? Can you point me to some document or example module that shows how to expose type information for TypeScript?

**Comment by mattnedrich** [comment]
@wrr Correct. Some (probably most) users will just use your library as vanilla JavaScript. TypeScript users can also use it, but since there are not types defined everything they import from `wwwhipser` is defined as an `any` type. This can conflict with some stricter TypeScript compiler settings.

To support TypeScript, JavaScript libraries can add a type definition file describing the type of each exported variable. There seem to be two ways to do this right now.

1) Add the type definition file directly to your library repository.
2) Add type definitions to the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) library. This is a community sourced library specifically for type definitions. The current TypeScript convention for using libraries defined in DefinitelyTyped is to include two packages - one for the library, and another for the type definitions. So for examples, if you publish `wwwhisper` type definitions in DefinitelyTyped, the convention would be to `npm install wwwhisper` and `npm install @types/wwwhisper`. This is pretty common.

I would say that #2 is the more common approach right now. Directions for submitting a pull request are in the DefinitelyTyped readme. You could also use those directions to add type defs directly to `wwwhisper`.

Great library by the way - it's really easy to use and works great!

**Comment by wrr** [comment]
Thank you for the explanation. I decided to go with the first of your proposed approaches because it is recommended for npm owners: http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

I run into some troubles to support the following import syntax:

    import * as wwwhisper from "connect-wwwhisper";

The issue is described: here https://github.com/Microsoft/TypeScript/issues/3612. My understanding of this issue is that modules that export a single function should be imported with:

    import wwwhisper = require("connect-wwwhisper");

I added a hack to support also the first syntax, but I'm not fully sure if it is a good idea to include such hack.
